<?php
/* 
 * Drupal 7 - inject our javascript, site wide, using drupal_add_js()
 *   and drupal_add_css().
 *
 * Drupal 8 - must rewrite this to use an asset libraries:
 *   https://www.drupal.org/node/2216195
 */

// load dependencies (we are using drupal's jQuery, btw to that
// doesn't need to be loaded here)
drupal_add_js('//cdnjs.cloudflare.com/ajax/libs/hopscotch/0.2.5/js/hopscotch.min.js', 'external');
drupal_add_js('//cdnjs.cloudflare.com/ajax/libs/js-cookie/2.0.4/js.cookie.min.js', 'external');
drupal_add_css('//cdnjs.cloudflare.com/ajax/libs/hopscotch/0.2.5/css/hopscotch.min.css', 'external');

// load the tour controller
drupal_add_js(drupal_get_path('module', 'lis_hopscotch_tours') .
              '/js/controller.js');

/**
 * Implements hook_menu().
 */
function lis_hopscotch_tours_menu() {
    $items['lis-tours/%/js'] = array(
        'page callback' => 'lis_hopscotch_tours_js_endpoint',
        'page arguments' => array(1),
        'access callback' => TRUE, // allow anonymous http
    );
    return $items;
}

// send requested javascript tour back to cliend
function lis_hopscotch_tours_js_endpoint($tourId) {
    $module_path = drupal_get_path('module', 'lis_hopscotch_tours');
    $file = "$module_path/tours/$tourId.js";
    drupal_add_http_header('Content-Type', 'application/javascript');
    readfile($file);
    drupal_exit();
}