<?php
/* 
 * Drupal 7 - inject our javascript, site wide, using drupal_add_js()
 *   and drupal_add_css().
 *
 * Drupal 8 - must rewrite this to use an asset libraries:
 *   https://www.drupal.org/node/2216195
 */

// we also depend on drupal's jQuery, however it *should*
// automatically get loaded.

drupal_add_js(
    '//cdnjs.cloudflare.com/ajax/libs/hopscotch/0.2.5/js/hopscotch.min.js',
    array(
        'type' => 'external',
        'group' => JS_LIBRARY,
    )
);
drupal_add_js(
    '//cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.0/js.cookie.min.js',
    array(
        'type' => 'external',
        'group' => JS_LIBRARY,
    )
);
drupal_add_css(
    '//cdnjs.cloudflare.com/ajax/libs/hopscotch/0.2.5/css/hopscotch.min.css',
    array(
        'type' => 'external',
        'group' => JS_LIBRARY,
    )
);


// load our tour controller. Enforce the loading order by using the 'group'.
$my_path = drupal_get_path('module', 'lis_hopscotch_tours');

drupal_add_js(
    $my_path . '/js/lisTours.js',
    array(
        'type' => 'file',
        'group' => JS_DEFAULT,
    )
);

/**
 * Implements hook_menu().
 */
function lis_hopscotch_tours_menu() {
    $items['lis-tours/%/js'] = array(
        'page callback' => 'lis_hopscotch_tours_js_endpoint',
        'page arguments' => array(1),
        'access callback' => TRUE, // allow anonymous http
    );
    return $items;
}

// send requested javascript tour back to client
function lis_hopscotch_tours_js_endpoint($tourId) {
    $my_path = drupal_get_path('module', 'lis_hopscotch_tours');
    $file = "$my_path/tours/$tourId.js";
    drupal_add_http_header('Content-Type', 'application/javascript');
    readfile($file);
    drupal_exit();
}